logger:
  handlers:
    # first handler is stderr
    - format:
        # format is joined with " "
        - <white><bold>{elapsed.seconds}.{elapsed.microseconds}</bold></white>
        - <level>{message}</level>
        - <magenta>{extra!r}</magenta>
        - <blue>{name}:{line}</blue>
      backtrace: false
  levels:
    - name: INFO
      color: <blue><bold>
    - name: DEBUG
      color: <cyan>
    - name: TRACE
      color: <white><dim>

levels:
  asyncio: info
  setuptools: info
  httpcore: info
  httpx: info
  jedi: info
  parso: info
