name: Check

on:
  push:
  pull_request:

# required by dorny/test-reporter
permissions:
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix develop -c make lint
        env:
          RUFF_FORMAT: github
      - run: git diff
        if: failure()
  test-matrix:
    runs-on: ubuntu-latest
    outputs:
      pythons: ${{ steps.set-matrix.outputs.pythons }}
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - id: set-matrix
        run: |
          SYSTEM=$(nix eval --impure --raw --expr builtins.currentSystem)
          PYTHONS=$(nix flake show --json | jq --raw-output ".devShells.\"$SYSTEM\"  | keys | .[1:] | values[]" | tr "\n" " ")
          echo "pythons=$PYTHONS" >> $GITHUB_OUTPUT
  test:
    needs: test-matrix
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python: ${{ fromJson(needs.test-matrix.outputs.pythons) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix develop ".#${{ matrix.python }}" -c make test-cov
        id: test
        env:
          ARGV: -vv
          COV_REPORT: html xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: tests/coverage-html
      - uses: coverallsapp/github-action@v2
        with:
          file: tests/coverage.xml
          flag-name: ${{ join(matrix.*, ' - ') }}
          parallel: true
  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: ${{ join(matrix.*, ',') }}
