name: Check

on:
  push:
  pull_request:

# required by dorny/test-reporter
permissions:
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: make lint
        env:
          RUFF_FORMAT: github
          SKIP: mypy
      - run: git diff
        if: failure()
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - unit
          - functional
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: make test-${{ matrix.test }}-cov
        id: test
        env:
          ARGV: --junit-xml=test-${{ matrix.test }}.xml --cov-fail-under=0 -vv
          COV_REPORT: html xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-html-${{ matrix.test }}
          path: tests/coverage-html-${{ matrix.test }}
      - uses: actions/upload-artifact@v4
        if: ${{ success() || (failure() && steps.test.conclusion == 'failure') }}
        with:
          name: test-${{ matrix.test}}-result
          path: test-${{ matrix.test }}.xml
      - uses: coverallsapp/github-action@v2
        with:
          file: tests/coverage-${{ matrix.test }}.xml
          flag-name: ${{ matrix.test }}
          parallel: true
  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: ${{ join(matrix.*, ',') }}
  test-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1.9.1
        with:
          artifact: /test-.*-result/
          name: Test Report
          path: test-*.xml
          reporter: java-junit
