name: Check

on:
  push:
  pull_request:

# required by dorny/test-reporter
permissions:
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix develop -c make lint
        env:
          RUFF_FORMAT: github
      - run: git diff
        if: failure()
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - id: set-matrix
        run: |
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
  test:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: nix-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          system: ${{ matrix.system }}
          devshell: ${{ matrix.name }}
      - run: nix develop ".#${{ matrix.name }}" -c make test-cov
        id: test
        env:
          ARGV: -vv
          COV_REPORT: html xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-html-${{ matrix.name }}-${{ matrix.system }}
          path: tests/coverage-html
      - uses: coverallsapp/github-action@v2
        with:
          file: tests/coverage.xml
          flag-name: ${{ matrix.name }}-${{ matrix.system }}
          parallel: true
  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
