name: Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: make lint
        env:
          RUFF_FORMAT: github
          SKIP: mypy
      - run: git diff
        if: failure()
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - unit
          - functional
    env:
      ARGV: --junit-xml=test-${{ matrix.test }}.xml -vv
      COV_REPORT: xml
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: make test-${{ matrix.test }}
        id: test
        env:
          COV_REPORT: html xml
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-html-${{ matrix.test }}
          path: coverage-html-${{ matrix.test }}
      - uses: actions/upload-artifact@v3
        if: ${{ success() || (failure() && steps.test.conclusion == 'failure') }}
        with:
          name: test-result
          path: test-${{ matrix.test }}.xml
      - uses: coverallsapp/github-action@v2
        with:
          file: coverage-${{ matrix.test }}.xml
          flag-name: ${{ matrix.test }}
          parallel: true
  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: ${{ join(matrix.*, ',') }}
